#apiVersion: v1
#kind: PersistentVolume
#metadata:
#  name: app-pv-1
#  namepsace: cms
#  labels:
#    type: local
#spec:
#  storageClassName: manual
#  capacity:
#    storage: 5Gi
#  accessModes:
#    - ReadWriteOnce
#  hostPath:
#    path: "/mnt/data"
#---
#apiVersion: v1
#kind: PersistentVolume
#metadata:
#  name: app-pv-2
#  namepsace: cms
#  labels:
#    type: local
#spec:
#  storageClassName: manual
#  capacity:
#    storage: 5Gi
#  accessModes:
#    - ReadWriteOnce
#  hostPath:
#    path: "/mnt/data"
