#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: mysql-pv-claim
#  namespace: cms
#  labels:
#    app: db
#spec:
#  storageClassName: manual
#  accessModes:
#    - ReadWriteOnce
#  resources:
#    requests:
#      storage: 5Gi
#---
#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: wp-pv-claim
#  namespace: cms
#  labels:
#    app: app
#spec:
#  storageClassName: manual
#  accessModes:
#    - ReadWriteOnce
#  resources:
#    requests:
#      storage: 5Gi
